name: sip_rusak
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  geocoding: ^4.0.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobile_scanner: ^4.0.0 # Gunakan versi terbaru
  image_picker: ^1.1.0 # <<< PASTIKAN INI ADA DAN INDENTASINYA BENAR



  flutter_lints: ^5.0.0




flutter:


  uses-material-design: true

  assets:
  - assets/images/logo.png
  - assets/images/on_board.png
  - assets/images/report.png
  - assets/images/login.png
  - assets/images/google.png
  - assets/images/sign_in.png
  - assets/images/location.png
  - assets/animation/animation1.json
  - assets/images/camera.png
  - assets/images/images.png
  - assets/images/amico.png